replicaCount: 1

image:
  repository: rickmortyapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  protocol: TCP

ingress:
  enabled: true
  className: nginx
  host: rickmorty.local
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
    - path: /healthcheck
      pathType: Prefix
      servicePort: 80
    - path: /characters
      pathType: Prefix
      servicePort: 80

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
